Default: &defaults
  database: Member-Manager.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Member-Manager_test.sqlite3
  <<: *defaults

Staging:
  database: Member-Manager_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Member-Manager_production.sqlite3
  poolsize: 100
  <<: *defaults
