Default: &defaults
  database: WebRegister.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: WebRegister_test.sqlite3
  <<: *defaults

Staging:
  database: WebRegister_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: WebRegister_production.sqlite3
  poolsize: 100
  <<: *defaults
